update 1.26.25.13
AnacondaRecipes/types-urllib3-feedstock pull request #2
Opened 2023-05-11 22:13 UTC by Arishamays1

2023-05-11 22:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_25qr9u6de7/clone/recipe/meta.yaml:20: missing_wheel: For pypi packages, wheel should be present in the host section
ERROR: /tmp/abs_25qr9u6de7/clone/recipe/meta.yaml:28: missing_imports_or_run_test_py: Python packages require imports or a python test file in tests.
ERROR: /tmp/abs_25qr9u6de7/clone/recipe/meta.yaml:39: missing_license_family: The recipe is missing the `about/license_family` key.
ERROR: /tmp/abs_25qr9u6de7/clone/recipe/meta.yaml:39: missing_documentation: The recipe is missing a doc_url or doc_source_url
ERROR: /tmp/abs_25qr9u6de7/clone/recipe/meta.yaml:39: missing_dev_url: The recipe is missing a dev_url
Errors were found

</details>

2023-05-15 18:10 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_0dmgd3njt4/clone/recipe/meta.yaml:30: missing_imports_or_run_test_py: Python packages require imports or a python test file in tests.
ERROR: /tmp/abs_0dmgd3njt4/clone/recipe/meta.yaml:43: missing_license_family: The recipe is missing the `about/license_family` key.
Errors were found

</details>

2023-05-15 18:13 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_9fvmh167cd/clone/recipe/meta.yaml:30: missing_imports_or_run_test_py: Python packages require imports or a python test file in tests.
ERROR: /tmp/abs_9fvmh167cd/clone/recipe/meta.yaml:44: invalid_license_family: The recipe has an incorrect `about/license_family` value.{}
Errors were found

</details>

2023-05-15 18:16 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_23x21clgj_/clone/recipe/meta.yaml:30: missing_imports_or_run_test_py: Python packages require imports or a python test file in tests.
Errors were found

</details>

2023-05-15 20:01 UTC, SC426 commented on recipe/meta.yaml
>    commands:
Can you try: 

```
imports:
- types-urllib3
```

2023-05-15 20:20 UTC, ViridianMelody requested changes
Looks good to me as long as the import from Steve's comment doesn't cause issues.

2023-05-16 07:06 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  skip: True  # [ py<38]
Redundant whitespace in `[ py<38]`

2023-05-16 19:31 UTC, SC426 commented on recipe/meta.yaml
>    commands:
I got it to work by importing `types`

2023-05-17 00:03 UTC, Arishamays1 commented on recipe/meta.yaml
> +  skip: True  # [ py<38]
Removed!

2023-05-17 00:09 UTC, Arishamays1 commented on recipe/meta.yaml
>    commands:
Thank you! Added

2023-05-17 07:02 UTC, skupr-anaconda approved these changes

2023-05-17 16:57 UTC, SC426 approved these changes

2023-05-17 18:20 UTC, ViridianMelody approved these changes

2023-05-17 20:45 UTC, schuylermartin45 commented
I managed to accidentally duplicate this work while trying to solve my own dependency issues. I will close my open PR (#3 ) in favor of this one.

2023-05-17 22:59 UTC, merged